name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        php-version: [8.2]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, bcmath, sqlite3
        coverage: xdebug

    - name: Install Composer dependencies
      run: cd backend && php ../composer install --no-dev --optimize-autoloader

    - name: Install Node dependencies
      run: cd frontend && npm ci

    - name: Run PHP tests
      run: cd backend && php artisan test

    - name: Run PHP linting
      run: cd backend && php ../vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Run TypeScript type checking
      run: cd frontend && npm run type-check

    - name: Run ESLint
      run: cd frontend && npm run lint

    - name: Build frontend
      run: cd frontend && npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Use PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, xml, ctype, json, bcmath, sqlite3

    - name: Install dependencies
      run: |
        php ./composer install --no-dev --optimize-autoloader
        cd frontend && npm ci

    - name: Build application
      run: |
        cd frontend && npm run build
        cp -r dist/* backend/public/app/

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/storage/app/**
          **/storage/framework/**
          **/storage/logs/**
          **/bootstrap/cache/**
          **/.env**
          **/composer.json
          **/composer.lock
          **/package.json
          **/package-lock.json
          **/vite.config.js
          **/tailwind.config.js
          **/postcss.config.js
          **/tsconfig.json
          **/tsconfig.node.json
          **/frontend/**
          **/deploy.sh
          **/.github/**
          **/.editorconfig
          **/.prettier*
          **/.eslint*
          **/.php-cs-fixer.php